### ISSUE TITLE
Example does not work with latest `remark-gfm@4.0.0`

### ISSUE THREAD

**Issue by zcolleyz** [storybookjs/mdx2-csf#45]
**Describe the bug**
Example does not work with latest `remark-gfm` version 4.0.0.  When you run it you get the following error:

```bash
#41 41.33 Module build failed (from ./node_modules/@storybook/mdx2-csf/loader.js):
#41 41.33 TypeError: Cannot read properties of undefined (reading 'inTable')
#41 41.33     at Object.exitCodeText (./node_modules/mdast-util-gfm-table/lib/index.js:82:17)
#41 41.33     at compile3 (./node_modules/@storybook/mdx2-csf/dist/index.js:95356:41)
#41 41.33     at fromMarkdown (./node_modules/@storybook/mdx2-csf/dist/index.js:95215:29)
#41 41.33     at parser (./node_modules/@storybook/mdx2-csf/dist/index.js:95936:12)
#41 41.33     at Function.parse9 [as parse] (./node_modules/@storybook/mdx2-csf/dist/index.js:81475:12)
#41 41.33     at executor (./node_modules/@storybook/mdx2-csf/dist/index.js:81535:31)
#41 41.33     at new Promise (<anonymous>)
#41 41.33     at Function.process3 [as process] (./node_modules/@storybook/mdx2-csf/dist/index.js:81530:14)
#41 41.33     at compile (./node_modules/@storybook/mdx2-csf/dist/index.js:101897:35)
#41 41.33     at compile2 (./node_modules/@storybook/mdx2-csf/dist/index.js:102304:30)
#41 41.33     at Object.loader (./node_modules/@storybook/mdx2-csf/loader.js:29:20)
```

**To Reproduce**

1. Install `remark-gfm at 4.0.0`
2. Apply the config from the documentation for `@storybook/addon-docs`
3. Run Storybook
4. See an error

**Expected behavior**

Runs as it did with v3.0.1

**Additional context**

This was tested through `@storybook/addon-docs` and so I don't know if the bug should be raised there instead, this seemed to be what consumes `remarkPlugins`

**Comment by vekunz** [comment]
We have this error as well. This blocks updating `remark-gfm` to `4.0.0`.
